#index:
#    path: /
#    controller: App\Controller\DefaultController::index
especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::buscarTodos
  methods:
    - GET

medicos:
  path: /medicos
  controller: App\Controller\MedicosController::buscarTodos
  methods:
    - GET